/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pruebas_de_codigo;

import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author santi
 */
public class pruebas extends javax.swing.JFrame {

    public static String fechaV = "";
    public static JDateChooser dateChooser;
    public byte[] imageBytes;

    public String enlaceOriginal = "C:\\Users\\santi\\Downloads\\Segundo consolidado\\Minimarket_Bases\\Minimarket_bases2\\src\\imagenes\\perfil_encontrado.png";

    public pruebas() {
        initComponents();
        dateChooser = new JDateChooser();
        jButton1.add(dateChooser);

        //JButton btnFecha = new JButton("Seleccionar Fecha");
        jButton1.setText("Seleccionar fecha");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dateChooser.setVisible(true);
            }
        });
//        getContentPane().add(btnFecha);

//        String enlaceConvertido = convertirEnlace(enlaceOriginal);
//        System.out.println(enlaceConvertido);

        String paht_com22= imgenEnviar(enlaceOriginal);
//        String cadenaOriginal = enlaceConvertido;
//        String palabra = "/imagenes";

//        String subcadena = obtenerSubcadena(cadenaOriginal, palabra);
        System.out.println(paht_com22);

        jLabel1.setText("");
        ImageIcon img_0 = new ImageIcon(getClass().getResource(paht_com22));
        ImageIcon foto_0 = new ImageIcon(img_0.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(foto_0);
    }

//    public String convertirEnlace(String enlace) {
//        // Reemplazar "\\" por "/"
//        String enlaceConvertido = enlace.replace("\\", "/");
//        return enlaceConvertido;
//
//    }
//
//    public String obtenerSubcadena(String cadena, String palabra) {
//        // Obtener el índice de la palabra en la cadena
//        int indice = cadena.indexOf(palabra);
//
//        if (indice != -1) {
//            // Obtener la subcadena a partir del índice de la palabra
//            String subcadena = cadena.substring(indice);
//            return subcadena;
//        } else {
//            // La palabra no se encontró en la cadena
//            return "";
//        }
//    }

    public String imgenEnviar(String enlace){
//        Reemplazar "\\" por "/"
        String enlaceConvertido = enlace.replace("\\", "/");
        
        
        String cadenaOriginal = enlaceConvertido;
        String palabra = "/imagenes";
        
        // Obtener el índice de la palabra en la cadena
        int indice = cadenaOriginal.indexOf(palabra);

        if (indice != -1) {
            // Obtener la subcadena a partir del índice de la palabra
            String subcadena = cadenaOriginal.substring(indice);
            return subcadena;
        } else {
            // La palabra no se encontró en la cadena
            return "";
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        jButton2.setText("imp");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date fechaVenci = dateChooser.getDate();
        SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");
        String fechaV = form.format(fechaVenci);
        System.out.println(fechaV);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
