/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import Modelo.MySQL;
import java.awt.Font;
import vista.Producto.frmiProducto;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import vista.Cliente.frmiCliente;
import vista.empresa.Empresa;

/**
 *
 * @author santi
 */
public class frmiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmiPrincipal
     */
    public static int nFils = 0;
    private frmiProducto producto = null;
    private frmiCliente cliente = null;
    private Empresa emp = null;

    private int ancho = 35, alto = 35;
    public static Font Helvetica = new Font("Helvetica", Font.ITALIC, 17);
    public static Font FontMenu = new Font("Helvetica", Font.ITALIC, 14);

    public frmiPrincipal() {
        //titulo
        setTitle("Minimarket");
        //Icono del formulario
        Image icon_inter = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/producto.png"));
        setIconImage(icon_inter);

        initComponents();

        //Seccion del menu
        fileMenu.setMnemonic('f');
        fileMenu.setText("Entidades");
        fileMenu.setFont(Helvetica);
        
        JmPrincipales.setText("Principales");
        JmPrincipales.setFont(Helvetica);

        jMIProducto.setText("Producto");
        jMIProducto.setFont(FontMenu);
        JmPrincipales.add(jMIProducto);

        jMICliente.setText("Cliente");
        jMICliente.setFont(FontMenu);
        JmPrincipales.add(jMICliente);

        jMIEmpresa.setFont(FontMenu);
        jMIEmpresa.setText("Empresa");
        JmPrincipales.add(jMIEmpresa);

        fileMenu.add(JmPrincipales);

        jMSecundarias.setText("Admin");
        jMSecundarias.setFont(Helvetica);

        jMIEmpleado.setText("Empleado");
        jMIEmpleado.setFont(FontMenu);
        jMSecundarias.add(jMIEmpleado);

        fileMenu.add(jMSecundarias);

        ItemExit.setMnemonic('x');
        ItemExit.setText("Cerrar Programa");
        ItemExit.setFont(Helvetica);
        fileMenu.add(ItemExit);

        menuBar.add(fileMenu);

        jMSecundarias.setEnabled(false);

        //BLoque por si no es admin
        if (Modelo.C_login.Val_admin == true) {
            jMSecundarias.setEnabled(true);
        }

        //Fin del seccion del menu nav
        setLocationRelativeTo(null);
        //setSize(700,600);
        setResizable(false);
        //setLayout(null);

        //ITEMS
        ImageIcon productoImg = new ImageIcon(getClass().getResource("/imagenes/Product.png"));
        ImageIcon MitadProductoImg = new ImageIcon(productoImg.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
        jMIProducto.setIcon(MitadProductoImg);

        ImageIcon clienteImg = new ImageIcon(getClass().getResource("/imagenes/Usuario.png"));
        ImageIcon MitadClienteImg = new ImageIcon(clienteImg.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
        jMICliente.setIcon(MitadClienteImg);

        ImageIcon empresaImg = new ImageIcon(getClass().getResource("/imagenes/Empresa.png"));
        ImageIcon MitadEmpresaImg = new ImageIcon(empresaImg.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
        jMIEmpresa.setIcon(MitadEmpresaImg);
        
        ImageIcon salirImg = new ImageIcon(getClass().getResource("/imagenes/Salir.png"));
        ImageIcon MitadSalirImg = new ImageIcon(salirImg.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
        ItemExit.setIcon(MitadSalirImg);
        
        ImageIcon empleadoImg = new ImageIcon(getClass().getResource("/imagenes/Empleado.png"));
        ImageIcon MitadEmpleadoImg = new ImageIcon(empleadoImg.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
        jMIEmpleado.setIcon(MitadEmpleadoImg);
        
        ImageIcon adminImg = new ImageIcon(getClass().getResource("/imagenes/Admin.png"));
        ImageIcon MitadAdminImg = new ImageIcon(adminImg.getImage().getScaledInstance(45, 45, Image.SCALE_SMOOTH));
        jMSecundarias.setIcon(MitadAdminImg);
        
        ImageIcon principalesImg = new ImageIcon(getClass().getResource("/imagenes/Principales.png"));
        ImageIcon MitadPrincipalesImg = new ImageIcon(principalesImg.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH));
        JmPrincipales.setIcon(MitadPrincipalesImg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        JmPrincipales = new javax.swing.JMenu();
        jMIProducto = new javax.swing.JMenuItem();
        jMICliente = new javax.swing.JMenuItem();
        jMIEmpresa = new javax.swing.JMenuItem();
        jMSecundarias = new javax.swing.JMenu();
        jMIEmpleado = new javax.swing.JMenuItem();
        ItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        JmPrincipales.setText("jMenu1");

        jMIProducto.setText("jMenuItem1");
        jMIProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProductoActionPerformed(evt);
            }
        });
        JmPrincipales.add(jMIProducto);

        jMICliente.setText("jMenuItem2");
        jMICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIClienteActionPerformed(evt);
            }
        });
        JmPrincipales.add(jMICliente);

        jMIEmpresa.setText("jMenuItem3");
        jMIEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEmpresaActionPerformed(evt);
            }
        });
        JmPrincipales.add(jMIEmpresa);

        fileMenu.add(JmPrincipales);

        jMSecundarias.setText("jMenu1");

        jMIEmpleado.setText("jMenuItem7");
        jMSecundarias.add(jMIEmpleado);

        fileMenu.add(jMSecundarias);

        ItemExit.setMnemonic('x');
        ItemExit.setText("Exit");
        ItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemExitActionPerformed(evt);
            }
        });
        fileMenu.add(ItemExit);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ItemExitActionPerformed

    private void jMIProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProductoActionPerformed
        try {

            if (producto == null || producto.isClosed()) {

                producto = new frmiProducto();
                this.desktopPane.add(producto);
                frmiProducto.contador = 0;
                frmiProducto.contador_edit = 0;

            }
            producto.setVisible(true);
            MySQL.Ctabla_prod();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "" + e);
        }
    }//GEN-LAST:event_jMIProductoActionPerformed

    private void jMIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIClienteActionPerformed
        if (cliente == null || cliente.isClosed()) {

            cliente = new frmiCliente();
            this.desktopPane.add(cliente);

        }
        cliente.setVisible(true);
    }//GEN-LAST:event_jMIClienteActionPerformed

    private void jMIEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEmpresaActionPerformed
        if (emp == null || emp.isClosed()) {

            emp = new Empresa();
            this.desktopPane.add(emp);

        }
        emp.setVisible(true);
    }//GEN-LAST:event_jMIEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemExit;
    private javax.swing.JMenu JmPrincipales;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jMICliente;
    private javax.swing.JMenuItem jMIEmpleado;
    private javax.swing.JMenuItem jMIEmpresa;
    private javax.swing.JMenuItem jMIProducto;
    private javax.swing.JMenu jMSecundarias;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
