/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import vista.frmiPrincipal;
import static vista.frmiPrincipal.nFils;

/**
 *
 * @author santi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static int pos_user = 0, ancho = 50, alto = 52;
    public static String[] usuarios = {"santi", "camilo", "alex", "sebas"};
    public static String[] Contra = {"1234", "12345", "123456", "1234567"};
    public static String[] prfImg = {"/imagenes/perf/santi.jpg", "/imagenes/perf/camilo.jpg", "/imagenes/perf/alex.jpg", "/imagenes/perf/sebas.jpg"};

    public Login() {
        String registros = JOptionPane.showInputDialog("Digite Cantidad de Registros:");
            nFils = Integer.parseInt(registros);

        //titulo
        setTitle("Login");
        
        //Icono del formulario
        Image icon_inter = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/producto.png"));
        setIconImage(icon_inter);
        initComponents();
        setLocationRelativeTo(null);
        setLayout(null);

        //labels
        //Lbl User
        jLuser.setForeground(new java.awt.Color(0, 0, 0));
        jLuser.setFont(new Font("Arial", Font.BOLD, 14));
        jLuser.setText("Usuario");
        //lbl Contraseña
        jLcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        jLcontraseña.setFont(new Font("Arial", Font.BOLD, 14));
        jLcontraseña.setText("Contraseña");
        //lbl foto
        ImageIcon PfotoI = new ImageIcon(getClass().getResource("/imagenes/informacion.png"));
        ImageIcon foto1_mitad = new ImageIcon(PfotoI.getImage().getScaledInstance(jLfoto.getWidth(), jLfoto.getHeight(), Image.SCALE_DEFAULT));
        jLfoto.setIcon(foto1_mitad);

        //cajas de texto
        //JtUser
        jTUser.setForeground(Color.GRAY);
        jTUser.setText("pepito");
        //JPFcontraseña
        jTcontraseña.setForeground(Color.GRAY);
        jTcontraseña.setText("*******");
        jTcontraseña.setEnabled(false);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLfoto = new javax.swing.JLabel();
        jLuser = new javax.swing.JLabel();
        jTUser = new javax.swing.JTextField();
        jLcontraseña = new javax.swing.JLabel();
        jTcontraseña = new javax.swing.JTextField();
        jPBlogin = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLfoto.setText("jLabel1");

        jLuser.setText("jLabel2");

        jTUser.setText("jTextField1");
        jTUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTUserFocusLost(evt);
            }
        });
        jTUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUserActionPerformed(evt);
            }
        });
        jTUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTUserKeyPressed(evt);
            }
        });

        jLcontraseña.setText("jLabel3");

        jTcontraseña.setText("jTextField1");
        jTcontraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTcontraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTcontraseñaFocusLost(evt);
            }
        });
        jTcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTcontraseñaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLuser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTUser, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jLcontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTcontraseña))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLuser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLcontraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTUserFocusGained
        jTUser.setForeground(Color.BLACK);
        jTUser.setText("");
    }//GEN-LAST:event_jTUserFocusGained

    private void jTUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTUserFocusLost
        jTUser.setForeground(Color.GRAY);
        jTUser.setText("pepito");
    }//GEN-LAST:event_jTUserFocusLost

    private void jTUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUserActionPerformed

    private void jTUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTUserKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Entramos");
            for (int i = 0; i < 4; i++) {
                if (jTUser.getText().equalsIgnoreCase(usuarios[i])) {
                    pos_user = i;
                    jTcontraseña.setEnabled(true);
                    JOptionPane.showMessageDialog(rootPane, "Hola " + usuarios[i] + ", escribe tu contraseña");
                    jTUser.setEnabled(false);
                    jTUser.setForeground(Color.GRAY);
                    jTUser.setText(usuarios[i]);
                    System.out.println(pos_user);
                }
            }
            if (jTcontraseña.isEnabled() == false) {
                JOptionPane.showMessageDialog(rootPane, "Usuario incorrecto");
                jTUser.setForeground(Color.BLACK);
                jTUser.setText("");
            }
        }

    }//GEN-LAST:event_jTUserKeyPressed

    private void jTcontraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTcontraseñaFocusGained
        jTcontraseña.setForeground(Color.BLACK);
        jTcontraseña.setText("");
    }//GEN-LAST:event_jTcontraseñaFocusGained

    private void jTcontraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTcontraseñaFocusLost
        jTcontraseña.setForeground(Color.GRAY);
        jTcontraseña.setText("*******");
    }//GEN-LAST:event_jTcontraseñaFocusLost

    private void jTcontraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcontraseñaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Entramos clave");
                if (jTcontraseña.getText().equalsIgnoreCase(Contra[pos_user])) {

                    ImageIcon Pfoto = new ImageIcon(getClass().getResource(prfImg[pos_user]));
                    ImageIcon foto_mitad = new ImageIcon(Pfoto.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
                    Object nivel = JOptionPane.showInputDialog(rootPane, "Cual es el Nivel del Usuario?", "Nivel del Usuario", JOptionPane.QUESTION_MESSAGE, foto_mitad,
                            new Object[]{"Administrador", "Usuario Comun"}, "Administrador");
                    JOptionPane.showMessageDialog(rootPane, nivel);
                    
                    jTcontraseña.setEnabled(false);

                    ImageIcon pFoto = new ImageIcon(getClass().getResource(prfImg[pos_user]));
                    ImageIcon icono = new ImageIcon(pFoto.getImage().getScaledInstance(jLfoto.getWidth(), jLfoto.getHeight(), Image.SCALE_DEFAULT));
                    jLfoto.setIcon(icono);
                    
                    Thread hilos = new Thread() {
                @Override
                public void run() {
                    for (int i = 0; i <= 100; i++) {
                        try {
                            Thread.sleep(10);
                            jPBlogin.setValue(i);
                            if (jPBlogin.getValue() == 100) {
                                dispose();
                                java.awt.EventQueue.invokeLater(new Runnable() {
                                    public void run() {
                                        new frmiPrincipal().setVisible(true);
                                    }
                                });

                            }
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            };
            hilos.start();

                }
            
            if (jTcontraseña.isEnabled() == true) {
                JOptionPane.showMessageDialog(rootPane, "contraseña incorrecto");
                jTcontraseña.setForeground(Color.BLACK);
                jTcontraseña.setText("");
            }

            
        }
    }//GEN-LAST:event_jTcontraseñaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLcontraseña;
    private javax.swing.JLabel jLfoto;
    private javax.swing.JLabel jLuser;
    private javax.swing.JProgressBar jPBlogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTUser;
    private javax.swing.JTextField jTcontraseña;
    // End of variables declaration//GEN-END:variables
}
