/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Modelo.MySQL;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author santi
 */
public class SingUp extends javax.swing.JFrame {

    public static JDateChooser dateChooser_singUp;
    public static String grupturnsec = "", grupNivelsec = "";
    public final int ancho = 15, alto = 15;
    private ButtonModel grupTurn, grupNivel;

    public SingUp() {

        //asignacion de partes antes del init
        setTitle("Minimarket");
        Image Micono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/producto.png"));
        setIconImage(Micono);
        setLayout(null);

        initComponents();

        //Metodo contenedor de los diseños de los componentes
        components();
        setLocationRelativeTo(null);
    }

    private void components() {

        //seteo de las cajas
        jTFape.setText("Apellido");
        jTFape.setForeground(Color.GRAY);
        jTFape.setColumns(5);

        jTFnom.setText("Nombre");
        jTFnom.setForeground(Color.GRAY);
        jTFnom.setColumns(5);

        jTFclave.setText("*****");
        jTFclave.setForeground(Color.GRAY);
        jTFclave.setColumns(5);

        //atributos a los labels
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setFont(new Font("Arial", Font.BOLD, 14));

        jLape.setForeground(new java.awt.Color(0, 0, 0));
        jLape.setFont(new Font("Arial", Font.BOLD, 14));

        jLclave.setForeground(new java.awt.Color(0, 0, 0));
        jLclave.setFont(new Font("Arial", Font.BOLD, 14));

        jLfecha.setForeground(new java.awt.Color(0, 0, 0));
        jLfecha.setFont(new Font("Arial", Font.BOLD, 14));

        jLnivel.setForeground(new java.awt.Color(0, 0, 0));
        jLnivel.setFont(new Font("Arial", Font.BOLD, 14));

        jLnom.setForeground(new java.awt.Color(0, 0, 0));
        jLnom.setFont(new Font("Arial", Font.BOLD, 14));

        jLturno.setForeground(new java.awt.Color(0, 0, 0));
        jLturno.setFont(new Font("Arial", Font.BOLD, 14));

        //btn fechVenci
        dateChooser_singUp = new JDateChooser();

        jBcontFech.add(dateChooser_singUp);
        jBcontFech.setEnabled(false);

        //radios
        buttonGroup1.add(jRBdiurno);
        buttonGroup1.add(jRBnocturno);

        //grupTurn = buttonGroup1.getSelection();
        buttonGroup2.add(jRBadmin);
        buttonGroup2.add(jRBempleado);
        //grupNivel = buttonGroup2.getSelection();

        jBregistrar.setEnabled(false);
    }

    private void rec_dat() {

        //Rectifiacar rbuton turno
        if (jRBdiurno.isSelected()) {
            grupturnsec = "D";
        } else if (jRBnocturno.isSelected()) {
            grupturnsec = "N";
        } else {
            grupturnsec = null;
        }

        //Rectifiacar rbuton nivel
        if (jRBadmin.isSelected()) {
            grupNivelsec = "admin";
        } else if (jRBempleado.isSelected()) {
            grupNivelsec = "empleado";
        } else {
            grupNivelsec = null;
        }

        if (jTFnom.getText().equals("Nombre") || jTFape.getText().equals("Apellido")
                || jTFclave.getText().equals("*****") || dateChooser_singUp.getDate() == null || grupturnsec == null || grupNivelsec == null) {
            System.out.println(grupturnsec);
            System.out.println(grupNivelsec);
            jBregistrar.setEnabled(false);
        } else {
            jBregistrar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLTitulo = new javax.swing.JLabel();
        jTFnom = new javax.swing.JTextField();
        jLnom = new javax.swing.JLabel();
        jLape = new javax.swing.JLabel();
        jTFape = new javax.swing.JTextField();
        jPturno = new javax.swing.JPanel();
        jLturno = new javax.swing.JLabel();
        jRBdiurno = new javax.swing.JRadioButton();
        jRBnocturno = new javax.swing.JRadioButton();
        jPfecha_nacimi = new javax.swing.JPanel();
        jLfecha = new javax.swing.JLabel();
        jBcontFech = new javax.swing.JButton();
        jPnivel = new javax.swing.JPanel();
        jLnivel = new javax.swing.JLabel();
        jRBadmin = new javax.swing.JRadioButton();
        jRBempleado = new javax.swing.JRadioButton();
        jPclave = new javax.swing.JPanel();
        jLclave = new javax.swing.JLabel();
        jTFclave = new javax.swing.JTextField();
        jBregistrar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Registrar Usuario");

        jTFnom.setText("jTextField1");
        jTFnom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFnomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFnomFocusLost(evt);
            }
        });

        jLnom.setText("Nombres:");

        jLape.setText("Apellidos:");

        jTFape.setText("jTextField1");
        jTFape.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFapeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFapeFocusLost(evt);
            }
        });

        jLturno.setText("Turno:");

        jRBdiurno.setText("Diurno");
        jRBdiurno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRBdiurnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRBdiurnoFocusLost(evt);
            }
        });
        jRBdiurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBdiurnoActionPerformed(evt);
            }
        });

        jRBnocturno.setText("Nocturno");
        jRBnocturno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRBnocturnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRBnocturnoFocusLost(evt);
            }
        });
        jRBnocturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBnocturnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPturnoLayout = new javax.swing.GroupLayout(jPturno);
        jPturno.setLayout(jPturnoLayout);
        jPturnoLayout.setHorizontalGroup(
            jPturnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPturnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPturnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLturno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPturnoLayout.createSequentialGroup()
                        .addGroup(jPturnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBdiurno, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRBnocturno, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPturnoLayout.setVerticalGroup(
            jPturnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPturnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLturno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBdiurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBnocturno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLfecha.setText("Fecha de nacimiento:");

        jBcontFech.setText("jButton1");

        javax.swing.GroupLayout jPfecha_nacimiLayout = new javax.swing.GroupLayout(jPfecha_nacimi);
        jPfecha_nacimi.setLayout(jPfecha_nacimiLayout);
        jPfecha_nacimiLayout.setHorizontalGroup(
            jPfecha_nacimiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPfecha_nacimiLayout.createSequentialGroup()
                .addGroup(jPfecha_nacimiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPfecha_nacimiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(jBcontFech, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPfecha_nacimiLayout.setVerticalGroup(
            jPfecha_nacimiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPfecha_nacimiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLfecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jBcontFech)
                .addGap(26, 26, 26))
        );

        jLnivel.setText("Nivel del usuario:");

        jRBadmin.setText("Administrador");
        jRBadmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRBadminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRBadminFocusLost(evt);
            }
        });
        jRBadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBadminActionPerformed(evt);
            }
        });

        jRBempleado.setText("Empleado");
        jRBempleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRBempleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRBempleadoFocusLost(evt);
            }
        });
        jRBempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBempleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnivelLayout = new javax.swing.GroupLayout(jPnivel);
        jPnivel.setLayout(jPnivelLayout);
        jPnivelLayout.setHorizontalGroup(
            jPnivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnivelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLnivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRBempleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnivelLayout.setVerticalGroup(
            jPnivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnivelLayout.createSequentialGroup()
                .addComponent(jLnivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBadmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRBempleado)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLclave.setText("Contraseña:");

        jTFclave.setText("jTextField1");
        jTFclave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFclaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFclaveFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPclaveLayout = new javax.swing.GroupLayout(jPclave);
        jPclave.setLayout(jPclaveLayout);
        jPclaveLayout.setHorizontalGroup(
            jPclaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPclaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPclaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLclave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFclave))
                .addContainerGap())
        );
        jPclaveLayout.setVerticalGroup(
            jPclaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPclaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLclave)
                .addGap(18, 18, 18)
                .addComponent(jTFclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBregistrar.setText("Registrar");
        jBregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBregistrarActionPerformed(evt);
            }
        });

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPclave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPturno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTFnom, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLnom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTFape, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLape, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPfecha_nacimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLnom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLape)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPturno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPfecha_nacimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBregistrar)
                            .addComponent(jBcancelar))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBnocturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBnocturnoActionPerformed
        rec_dat();
    }//GEN-LAST:event_jRBnocturnoActionPerformed

    private void jTFnomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFnomFocusGained
        if (jTFnom.getText().equals("Nombre")) {
            jTFnom.setForeground(Color.BLACK);
            jTFnom.setText("");
            rec_dat();
        }
    }//GEN-LAST:event_jTFnomFocusGained

    private void jTFnomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFnomFocusLost
        if (!jTFnom.getText().isEmpty()) {

        } else {
            jTFnom.setForeground(Color.GRAY);
            jTFnom.setText("Nombre");
            rec_dat();
        }
    }//GEN-LAST:event_jTFnomFocusLost

    private void jTFapeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFapeFocusGained
        if (jTFape.getText().equals("Apellido")) {
            jTFape.setForeground(Color.BLACK);
            jTFape.setText("");
            rec_dat();
        }
    }//GEN-LAST:event_jTFapeFocusGained

    private void jTFapeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFapeFocusLost
        if (!jTFape.getText().isEmpty()) {

        } else {
            jTFape.setForeground(Color.GRAY);
            jTFape.setText("Apellido");
            rec_dat();
        }
    }//GEN-LAST:event_jTFapeFocusLost

    private void jTFclaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFclaveFocusGained
        if (jTFclave.getText().equals("*****")) {
            jTFclave.setForeground(Color.BLACK);
            jTFclave.setText("");
            rec_dat();
        }
    }//GEN-LAST:event_jTFclaveFocusGained

    private void jTFclaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFclaveFocusLost
        if (!jTFclave.getText().isEmpty()) {

        } else {
            jTFclave.setForeground(Color.GRAY);
            jTFclave.setText("*****");
            rec_dat();
        }
    }//GEN-LAST:event_jTFclaveFocusLost

    private void jBregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBregistrarActionPerformed

        //Obtencion de la fecha de vencimiento
        Date fechaNaci = dateChooser_singUp.getDate();
        SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");
        String fechaN = form.format(fechaNaci);

        Date fechaActual = new Date();
        long diffMilis = fechaActual.getTime() - fechaNaci.getTime();
        long milisPorAno = 1000L * 60 * 60 * 24 * 365;
        long edad = diffMilis / milisPorAno;


        String edad_emp_F = Long.toString(edad);

        MySQL.insert_empl("empleados", jTFnom.getText(), jTFape.getText(), jTFclave.getText(), grupturnsec, grupNivelsec, fechaN, edad_emp_F);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginM ln = new LoginM();
                ln.setVisible(true);
                setVisible(false);
            }
        });

    }//GEN-LAST:event_jBregistrarActionPerformed

    private void jRBdiurnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBdiurnoFocusGained
        rec_dat();
    }//GEN-LAST:event_jRBdiurnoFocusGained

    private void jRBdiurnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBdiurnoFocusLost
        rec_dat();
    }//GEN-LAST:event_jRBdiurnoFocusLost

    private void jRBnocturnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBnocturnoFocusGained
        rec_dat();
    }//GEN-LAST:event_jRBnocturnoFocusGained

    private void jRBnocturnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBnocturnoFocusLost
        rec_dat();
    }//GEN-LAST:event_jRBnocturnoFocusLost

    private void jRBadminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBadminFocusGained
        rec_dat();
    }//GEN-LAST:event_jRBadminFocusGained

    private void jRBadminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBadminFocusLost
        rec_dat();
    }//GEN-LAST:event_jRBadminFocusLost

    private void jRBempleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBempleadoFocusGained
        rec_dat();
    }//GEN-LAST:event_jRBempleadoFocusGained

    private void jRBempleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRBempleadoFocusLost
        rec_dat();
    }//GEN-LAST:event_jRBempleadoFocusLost

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginM ln = new LoginM();
                ln.setVisible(true);
                setVisible(false);
            }
        });
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jRBdiurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBdiurnoActionPerformed
        rec_dat();
    }//GEN-LAST:event_jRBdiurnoActionPerformed

    private void jRBadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBadminActionPerformed
        rec_dat();
    }//GEN-LAST:event_jRBadminActionPerformed

    private void jRBempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBempleadoActionPerformed
        rec_dat();
    }//GEN-LAST:event_jRBempleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBcontFech;
    private javax.swing.JButton jBregistrar;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLape;
    private javax.swing.JLabel jLclave;
    private javax.swing.JLabel jLfecha;
    private javax.swing.JLabel jLnivel;
    private javax.swing.JLabel jLnom;
    private javax.swing.JLabel jLturno;
    private javax.swing.JPanel jPclave;
    private javax.swing.JPanel jPfecha_nacimi;
    private javax.swing.JPanel jPnivel;
    private javax.swing.JPanel jPturno;
    private javax.swing.JRadioButton jRBadmin;
    private javax.swing.JRadioButton jRBdiurno;
    private javax.swing.JRadioButton jRBempleado;
    private javax.swing.JRadioButton jRBnocturno;
    private javax.swing.JTextField jTFape;
    private javax.swing.JTextField jTFclave;
    private javax.swing.JTextField jTFnom;
    // End of variables declaration//GEN-END:variables
}
